import { 
  Bed, Utensils, Sun, GraduationCap, Briefcase, Trees, Sparkles, MapPin, HeartHandshake, Box,
  Waves, Wifi, Coffee, Car, Shield, Tv, Wind, Thermometer, User, Users, Phone, Mail, 
  Calendar, Clock, Map, Star, Award, Heart, Camera, Image, Music, Film, ShoppingBag, 
  Tent, Mountain, Plane, Train, Bike, Dumbbell, GlassWater, Pizza, IceCream,
  Activity, Zap, Landmark, Building, Home, Key, Lock, Settings, Info
} from 'lucide-react';

export const ICONS = {
  bed: Bed,
  utensils: Utensils,
  sun: Sun,
  'graduation-cap': GraduationCap,
  briefcase: Briefcase,
  trees: Trees,
  sparkles: Sparkles,
  'map-pin': MapPin,
  'heart-handshake': HeartHandshake,
  box: Box,
  waves: Waves,
  wifi: Wifi,
  coffee: Coffee,
  car: Car,
  shield: Shield,
  tv: Tv,
  wind: Wind,
  thermometer: Thermometer,
  user: User,
  users: Users,
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  clock: Clock,
  map: Map,
  star: Star,
  award: Award,
  heart: Heart,
  camera: Camera,
  image: Image,
  music: Music,
  film: Film,
  'shopping-bag': ShoppingBag,
  tent: Tent,
  mountain: Mountain,
  plane: Plane,
  train: Train,
  bike: Bike,
  dumbbell: Dumbbell,
  'glass-water': GlassWater,
  pizza: Pizza,
  'ice-cream': IceCream,
  activity: Activity,
  zap: Zap,
  landmark: Landmark,
  building: Building,
  home: Home,
  key: Key,
  lock: Lock,
  settings: Settings,
  info: Info
};

export const ICON_OPTIONS = Object.keys(ICONS).map(key => ({
  name: key,
  Icon: ICONS[key]
}));
